theme: minima
title: So many Nerdbirds, so little time..
author: Nicole Ryan
description: > # this means to ignore newlines until "baseurl:"
  Nerdbird Farm is the family farm of Nicole and Max Ryan and their beloved foul and doggos. 

# social links
github_username:  nlryan

show_excerpts: true # set to false to remove excerpts on the homepage
