title: Just a bunch of Nerdbirds
author: Nicole Ryan
description: > # this means to ignore newlines until "baseurl:"
  Nerdbird Farm is the family farm or Nicole & Max Ryan, Samuel L Quackson & Gary, our resident ducks, a herd of chickens and our faithful doggos - Mr. Coop & Marvin. 

# social links
tiktok_username: nerdbirdfarm
github_username:  nlryan
facebook_username: nicoleryannn

show_excerpts: true # set to false to remove excerpts on the homepage
